name: password_keeper
description: Password Keeper

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^0.1.3
  sqflite: ^1.3.0
  path_provider: ^1.6.5
  intl: ^0.16.1
  url_launcher: ^5.4.2
  intro_views_flutter: ^2.8.0
  system_setting: ^0.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - assets/PasswordKeeperGifSS.gif
    - assets/PasswordKeeperLogo.png
    - assets/PasswordKeeperGif.gif
    - assets/PasswordKeeper1.png
    - assets/PasswordKeeper2.png
    - assets/PasswordKeeper3.png